default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost
development:
  <<: *default
  database: eat_project_development
test:
  <<: *default
  database: eat_project_test
production:
  <<: *default
  <% if Rails.application.credentials.db.present? %>
  database: eat_project_production
  username: root  
  password: <%=Rails.application.credentials.db[:password]%>
  host: <%=Rails.application.credentials.db[:hostname]%>  
  <% end %>